# Generated by Django 5.1.1 on 2024-10-06 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_favorite_is_read_like_is_read_share_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='share',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='view',
            name='is_read',
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(max_length=100, null=True)),
                ('content', models.TextField(max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
