# Generated by Django 5.1.1 on 2024-10-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_favorite_is_read_remove_like_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
