# Generated by Django 5.1.1 on 2024-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title',
            new_name='bio',
        ),
    ]
