# Generated by Django 5.1.1 on 2024-09-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authrefreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='tiktok_id',
        ),
    ]
