# Generated by Django 5.1.1 on 2024-09-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_id_user_tiktok_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
